#!/usr/bin/env python
"""mission.py — execute pre-computed cooperative payload trajectories.

This script uploads 7th-degree polynomial trajectory CSVs (produced by
``crazyflo_solve.py``) to a swarm of Crazyflies and runs them in a
button-gated sequence:

    1. takeoff     – all drones climb to INITIAL_HEIGHT in formation.
    2. align XY    – each drone moves horizontally above its trajectory
                     start point while staying at INITIAL_HEIGHT.
    3. descend     – each drone lowers to its exact trajectory start pose
                     (full 3-D position + yaw).
    4. fly         – all drones execute their trajectories simultaneously.
    5. land        – all drones land.

Pre-requisites
--------------
- Crazyswarm2 server running (``ros2 launch crazyflo_planner real.launch.xml``).
- ``data/traj_cf{1,2,3}.csv`` present (generated by crazyflo_solve.py).
- A joystick / button device mapped in the Crazyswarm2 input config.

Usage
-----
    python mission.py
"""

from pathlib import Path

from crazyflie_py import Crazyswarm
from crazyflie_py.uav_trajectory import Trajectory

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------

# Playback speed factor: 1.0 = real time, >1.0 = slower, <1.0 = faster.
TIMESCALE = 1.0

# Extra sleep added after a collective command to ensure all drones have
# settled before the next phase begins.
BUFFER_TIME = 2.0  # [s]

# Duration for the initial take-off command.
TAKEOFF_TIME = 2.0  # [s]

# Hover height used during the alignment phases before entering the trajectory.
INITIAL_HEIGHT = 0.4  # [m]

# Duration for the landing command.
LANDING_TIME = 2.0  # [s]

# Root directory; update if the workspace is mounted at a different path.
# ROOT_FOLDER = Path.home() / ".ros/crazyflo_planner"
ROOT_FOLDER = Path.home() / "winter-project/ws/"

data_path = ROOT_FOLDER / "data"


def main():
    """Run the Crazyflie swarm with predefined trajectories.

    The function blocks at each ``waitUntilButtonPressed()`` call so the
    operator can visually confirm the drone state before advancing to the
    next phase.
    """
    swarm = Crazyswarm()
    timeHelper = swarm.timeHelper
    allcfs = swarm.allcfs

    # ------------------------------------------------------------------
    # Load trajectory CSVs
    # One CSV per drone; if fewer CSVs than drones exist, the last CSV
    # is reused for the extra drones.
    # ------------------------------------------------------------------
    csv_cf1 = data_path / 'traj_cf1.csv'
    csv_cf2 = data_path / 'traj_cf2.csv'
    csv_cf3 = data_path / 'traj_cf3.csv'

    csv_paths = [csv_cf1, csv_cf2, csv_cf3]

    # Pad the list if the swarm has more than 3 drones
    while len(csv_paths) < len(allcfs.crazyflies):
        csv_paths.append(csv_paths[-1])

    traj_cfs = []
    for i in range(len(allcfs.crazyflies)):
        print(f"loading trajectory for cf{i+1} from {csv_paths[i]}")
        traj_cfs.append(Trajectory())
        traj_cfs[i].loadcsv(csv_paths[i])

    # Enable on-board SD-card logging before flight
    allcfs.setParam('usd.logging', 1)

    # ------------------------------------------------------------------
    # Upload trajectories to firmware
    # trajectory id = 0, start_index = 0 for all drones
    # ------------------------------------------------------------------
    print('uploading trajectories to crazyflies...')
    for i, cf in enumerate(allcfs.crazyflies):
        cf.uploadTrajectory(0, 0, traj_cfs[i])

    # ------------------------------------------------------------------
    # Phase 1: Takeoff
    # ------------------------------------------------------------------
    print('press button to takeoff...')
    swarm.input.waitUntilButtonPressed()
    allcfs.takeoff(targetHeight=INITIAL_HEIGHT, duration=TAKEOFF_TIME)
    timeHelper.sleep(BUFFER_TIME)  # wait for all drones to reach hover height

    # Move each drone to its (x, y) start position at INITIAL_HEIGHT,
    # setting the correct yaw so the subsequent descent is a pure Z motion.
    for i, cf in enumerate(allcfs.crazyflies):
        start = traj_cfs[i].eval(0.0)  # evaluate trajectory at t=0
        x, y, _ = start.pos
        yaw0 = start.yaw
        cf.goTo((x, y, INITIAL_HEIGHT), yaw0, 2.0)

    # ------------------------------------------------------------------
    # Phase 2: Align to trajectory start (3-D position + yaw)
    # ------------------------------------------------------------------
    print('press button to go to start position...')
    swarm.input.waitUntilButtonPressed()
    for i, cf in enumerate(allcfs.crazyflies):
        start = traj_cfs[i].eval(0.0)
        p0 = start.pos   # full 3-D start position from the trajectory
        yaw0 = start.yaw
        cf.goTo(p0, yaw0, 4.0)  # slower move to allow payload to settle

    # ------------------------------------------------------------------
    # Phase 3: Execute trajectory
    # All drones start simultaneously (broadcast command).
    # TIMESCALE can be increased to slow down playback for safety testing.
    # ------------------------------------------------------------------
    print('press button to start trajectory...')
    swarm.input.waitUntilButtonPressed()
    allcfs.startTrajectory(0, timescale=TIMESCALE)
    # Optional: block until trajectory finishes instead of using a button:
    # timeHelper.sleep(traj_cfs[0].duration * TIMESCALE + BUFFER_TIME)

    # ------------------------------------------------------------------
    # Phase 4: Land
    # ------------------------------------------------------------------
    print('press button to land...')
    swarm.input.waitUntilButtonPressed()
    allcfs.land(targetHeight=0.03, duration=LANDING_TIME)
    timeHelper.sleep(BUFFER_TIME)

    # Disable SD-card logging after landing


if __name__ == '__main__':
    main()
